/************************************************************************************************
** File created by QxEntityEditor 1.2.2 (2017/09/29 00:34) : please, do NOT modify this file ! **
************************************************************************************************/

#ifndef _DARYADB_V_KOL_MOIN_H_
#define _DARYADB_V_KOL_MOIN_H_

class DARYADB_EXPORT v_kol_moin
{

   QX_REGISTER_FRIEND_CLASS(v_kol_moin)

protected:

   long m_qx_ee_no_id; //!< Auto-generated by QxEntityEditor importer because there is no id defined
   long m_code;
   QString m_name;
   long m_moin_code;
   QString m_moin_name;

public:

   v_kol_moin();
   v_kol_moin(const long & id);
   virtual ~v_kol_moin();

   long getcode() const;
   QString getname() const;
   long getmoin_code() const;
   QString getmoin_name() const;

   void setcode(const long & val);
   void setname(const QString & val);
   void setmoin_code(const long & val);
   void setmoin_name(const QString & val);

public:

   static QString column_code(bool key = false) { Q_UNUSED(key); return "code"; }
   static QString column_name(bool key = false) { Q_UNUSED(key); return "name"; }
   static QString column_moin_code(bool key = false) { Q_UNUSED(key); return "moin_code"; }
   static QString column_moin_name(bool key = false) { Q_UNUSED(key); return "moin_name"; }

public:

   static QString table_name(bool key = false) { Q_UNUSED(key); return "v_kol_moin"; }

};

typedef std::shared_ptr<v_kol_moin> v_kol_moin_ptr;
typedef QList<v_kol_moin_ptr> list_of_v_kol_moin;
typedef std::shared_ptr<list_of_v_kol_moin> list_of_v_kol_moin_ptr;

QX_REGISTER_COMPLEX_CLASS_NAME_HPP_DARYADB(v_kol_moin, qx::trait::no_base_class_defined, 0, v_kol_moin)

#include "../custom/include/v_kol_moin.h"

#endif // _DARYADB_V_KOL_MOIN_H_
